[server]
port = 8080
host = "127.0.0.1"

[database]
url = "sqlite://coterie.db"
max_connections = 5

[auth]
session_secret = "change-me-in-production-please-use-something-secure"
session_duration_hours = 24

[features]
discord_integration = false
unifi_integration = false
payments = false

[discord]
bot_token = ""
guild_id = ""
member_role_id = ""

[unifi]
controller_url = ""
username = ""
password = ""
site_id = "default"

[stripe]
publishable_key = ""
secret_key = ""
webhook_secret = ""