/// Marker comment written to the generated /etc/caddy/Caddyfile so the
/// idempotency check can recognize a wizard-managed file vs. an
/// operator-edited one.
pub const COTERIE_MARKER: &str = "# Generated by coterie-provision.";

/// Render the operator's Caddyfile from `Caddyfile.example`.
///
/// Substitutions:
///   - `coterie.example.com` → portal_domain
///   - second site block (`example.com, www.example.com`) is removed
///     when no marketing domain is supplied; otherwise its `example.com`
///     reference becomes the marketing domain.
pub fn render_caddyfile(
    template: &str,
    portal_domain: &str,
    marketing_domain: Option<&str>,
) -> String {
    let with_portal = template.replace("coterie.example.com", portal_domain);
    let body = match marketing_domain {
        Some(m) => with_portal.replace("example.com", m),
        None => strip_marketing_block(&with_portal),
    };
    format!("{COTERIE_MARKER}\n{body}")
}

fn strip_marketing_block(input: &str) -> String {
    // The Caddyfile.example puts the marketing site behind a clearly
    // delimited section heading. We strip from that heading to the
    // matching closing brace at column 0.
    let marker = "# Public marketing";
    let Some(start) = input.find(marker) else {
        return input.to_string();
    };
    // Walk back to the divider line if present so we don't leave a
    // dangling separator.
    let head = &input[..start];
    let trimmed_head = trim_trailing_divider(head);
    let tail = &input[start..];
    let Some(open_brace) = tail.find('{') else {
        return trimmed_head;
    };
    let after_open = open_brace + 1;
    let mut depth = 1i32;
    let mut end = after_open;
    for (i, ch) in tail[after_open..].char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = after_open + i + 1;
                    break;
                }
            }
            _ => {}
        }
    }
    let rest = &tail[end..];
    format!("{trimmed_head}{}", rest.trim_start_matches('\n'))
}

fn trim_trailing_divider(head: &str) -> String {
    // Remove a trailing "# ---" divider line plus any trailing blank
    // line so the result reads cleanly without the marketing block.
    let mut s = head.trim_end_matches('\n').to_string();
    while let Some(idx) = s.rfind('\n') {
        let last = &s[idx + 1..];
        if last.trim_start().starts_with("# --") || last.trim().is_empty() {
            s.truncate(idx);
        } else {
            break;
        }
    }
    s.push('\n');
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    const TEMPLATE: &str = include_str!("../../Caddyfile.example");

    #[test]
    fn portal_only_strips_marketing_block() {
        let out = render_caddyfile(TEMPLATE, "coterie.example.org", None);
        assert!(out.contains(COTERIE_MARKER));
        assert!(out.contains("coterie.example.org {"));
        assert!(!out.contains("example.com, www.example.com"));
        assert!(!out.contains("Public marketing"));
    }

    #[test]
    fn portal_plus_marketing_substitutes() {
        let out = render_caddyfile(TEMPLATE, "coterie.example.org", Some("example.org"));
        assert!(out.contains("coterie.example.org {"));
        assert!(out.contains("example.org, www.example.org {"));
        assert!(out.contains("Public marketing"));
    }

    #[test]
    fn hyphenated_subdomain() {
        let out = render_caddyfile(TEMPLATE, "my-coterie.deep.sub.example.net", None);
        assert!(out.contains("my-coterie.deep.sub.example.net {"));
    }

    #[test]
    fn marker_is_first_line() {
        let out = render_caddyfile(TEMPLATE, "coterie.example.org", None);
        assert_eq!(out.lines().next(), Some(COTERIE_MARKER));
    }
}
