//! CSRF token service. Stateless: tokens are `nonce || HMAC(key, session_id || nonce)`
//! hex-encoded, validated by recomputing the MAC with constant-time comparison.
//!
//! **Why stateless.** The previous per-session DB design overwrote the
//! token on every `generate_token` call, which broke multi-tab admin
//! workflows. HMAC has no such problem — any tab can generate any
//! number of tokens for the same session, and they all validate
//! independently until the session itself expires.
//!
//! The `csrf_tokens` table is dropped by migration 010; the
//! `delete_token` / `cleanup_orphaned` methods remain as no-ops so
//! existing callers (logout cleanup, background task) compile unchanged.

use hmac::{Hmac, Mac};
use rand::{RngCore, rngs::OsRng};
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;

use crate::error::Result;

type HmacSha256 = Hmac<Sha256>;

/// Nonce length in bytes. 128 bits is overkill for uniqueness but the
/// extra bytes are cheap and make accidental collisions impossible.
const NONCE_LEN: usize = 16;
/// HMAC-SHA256 output length.
const MAC_LEN: usize = 32;
const TOKEN_LEN: usize = NONCE_LEN + MAC_LEN;

pub struct CsrfService {
    /// HMAC key, derived from the application's session_secret with
    /// domain separation.
    key: [u8; 32],
}

impl CsrfService {
    /// Construct a service keyed off the application's session_secret.
    /// If the secret is rotated, existing tokens become invalid (users
    /// submitting forms during the rotation get a 403 and retry).
    pub fn new(session_secret: &str) -> Self {
        let mut hasher = Sha256::new();
        hasher.update(b"coterie-csrf-v1|");
        hasher.update(session_secret.as_bytes());
        let key: [u8; 32] = hasher.finalize().into();
        Self { key }
    }

    /// Generate a fresh CSRF token scoped to the given session.
    /// Async signature kept for API compatibility; no IO happens.
    pub async fn generate_token(&self, session_id: &str) -> Result<String> {
        let mut nonce = [0u8; NONCE_LEN];
        OsRng.fill_bytes(&mut nonce);
        let mac = self.mac(session_id, &nonce);

        let mut out = Vec::with_capacity(TOKEN_LEN);
        out.extend_from_slice(&nonce);
        out.extend_from_slice(&mac);
        Ok(hex::encode(out))
    }

    /// Verify that `token` was generated by this service for the given
    /// session. Returns false for any malformed or wrong-session token
    /// without leaking timing info about which part failed.
    pub async fn validate_token(&self, session_id: &str, token: &str) -> Result<bool> {
        let bytes = match hex::decode(token) {
            Ok(b) if b.len() == TOKEN_LEN => b,
            _ => return Ok(false),
        };
        let (nonce, provided_mac) = bytes.split_at(NONCE_LEN);
        let expected_mac = self.mac(session_id, nonce);
        Ok(expected_mac.ct_eq(provided_mac).into())
    }

    fn mac(&self, session_id: &str, nonce: &[u8]) -> [u8; MAC_LEN] {
        // HmacSha256::new_from_slice accepts any length; our 32-byte
        // key is well within bounds so unwrap is safe.
        let mut mac = HmacSha256::new_from_slice(&self.key).expect("HMAC key length valid");
        mac.update(session_id.as_bytes());
        mac.update(b"|");
        mac.update(nonce);
        mac.finalize().into_bytes().into()
    }

    /// No-op in the stateless design. Kept for API compatibility with
    /// the old DB-backed implementation.
    pub async fn delete_token(&self, _session_id: &str) -> Result<()> {
        Ok(())
    }

    /// No-op: there's nothing to clean up. Kept for API compatibility
    /// with the background cleanup loop in main.rs.
    pub async fn cleanup_orphaned(&self) -> Result<u64> {
        Ok(0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn round_trip() {
        let svc = CsrfService::new("test-secret");
        let token = svc.generate_token("session-A").await.unwrap();
        assert!(svc.validate_token("session-A", &token).await.unwrap());
    }

    #[tokio::test]
    async fn rejects_wrong_session() {
        let svc = CsrfService::new("test-secret");
        let token = svc.generate_token("session-A").await.unwrap();
        assert!(!svc.validate_token("session-B", &token).await.unwrap());
    }

    #[tokio::test]
    async fn rejects_different_secret() {
        let a = CsrfService::new("secret-one");
        let b = CsrfService::new("secret-two");
        let token = a.generate_token("session").await.unwrap();
        assert!(!b.validate_token("session", &token).await.unwrap());
    }

    #[tokio::test]
    async fn rejects_malformed() {
        let svc = CsrfService::new("x");
        assert!(!svc.validate_token("s", "").await.unwrap());
        assert!(!svc.validate_token("s", "not-hex").await.unwrap());
        assert!(!svc.validate_token("s", "deadbeef").await.unwrap()); // too short
        assert!(!svc.validate_token("s", &"ab".repeat(100)).await.unwrap()); // too long
    }

    #[tokio::test]
    async fn tokens_are_unique_per_generate() {
        let svc = CsrfService::new("x");
        let a = svc.generate_token("s").await.unwrap();
        let b = svc.generate_token("s").await.unwrap();
        assert_ne!(a, b, "nonces should make every token unique");
        // BOTH tokens should validate — this is the key property that
        // makes multi-tab use work, which the old design broke.
        assert!(svc.validate_token("s", &a).await.unwrap());
        assert!(svc.validate_token("s", &b).await.unwrap());
    }
}
